import { Router } from "express";
import { OauthController } from "../controllers/auth/oauthController";
import { OauthCallBackController } from "../controllers/auth/oauthCallback.controller";
import { getUserController } from "../controllers/user/getUser.controller";
import { logoutController } from "../controllers/auth/logout.controller";
const userRouter = Router();
userRouter.route("/oauth").get(OauthController);
userRouter.route("/oauth/callback").get(OauthCallBackController);
userRouter.route("/user").get(getUserController).delete(logoutController);
export default userRouter;
